version: '3.8'
services:
  web:
    build: .
    ports:
      - "8088:5000"
    volumes:
      - .:/src
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
  redis:
    image: "redis:alpine"