version: '3'
services:
  web:
    build: .
    ports:
      - "9999:9999"
    networks:
      - my-network
    depends_on:
      - redis
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - my-network
networks:
  my-network: